name: diss
channels:
  - conda-forge
dependencies:
  - python=3.14
  - cadet>=5.1.0
  - jupyter-book<2.0
  - jupyter_contrib_nbextensions
  - jupytext
  - matplotlib
  - mdformat-myst
  - numpy
  - scipy
  - pytest
  - tabulate
  - pip
  - pip:
      - cadet-rdm>=1.0.0
      - cadet-process>=0.11.1
