name: diss
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - cadet>=5.0.4
  - mdformat-myst
  - jupyter-book
  - jupyter_contrib_nbextensions
  - jupytext
  - tabulate
  - pip
  - pip:
      - cadet-rdm>=0.1.8
      - cadet-process>=0.11.1
